routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::get('/test', function () {
    //     return view('admin.template.master');
    // });
    
    
// Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
return view('welcome');
});


// Route::get('/user/book', function () {
    // return view('user.layouts.book');
    // });
    // Route::get('/admin/listusers', function(){
        //     return view('admin.layout.component.listusers.table');
        // });

        
        Auth::routes();
        
        // Route::get('/admin', function (){
//     return view('admin.layout.home');
// })->middleware('auth');



Route::get('/excel-user', 'Admin\ListuserController@export');
Route::get('/excel-book', 'Admin\BookController@export');
Route::resource('create-profile', 'User\ProfileController')->middleware('auth');

Route::get('/admin', 'Admin\AdminController@index');
Route::resource('admin/books', 'Admin\BookController')->middleware('auth');
Route::resource('admin/listusers', 'Admin\ListuserController')->middleware('auth');

Route::get('/user', 'User\UserController@home');
Route::resource('user/book', 'User\UserController')->middleware('auth');
Route::get('/user/history', 'User\UserController@history')->middleware('auth');

app/books.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Books extends Model
{
    protected $table = "books";
    protected $fillable = ['title','author','publish'];
}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Exports\BooksExport;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Http\Request;
use App\Books;
use App\genres;
use DB;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $book = Books::all();
    	return view('admin.layout.component.books.table',['books' => $book]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.layout.component.books.form');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|unique:books',
            'author' => 'required',
            'publish' =>'required',
        ]);
        

        // dd($request->all());
        
        if($request["genre"] !== null) {
            $tmp = strtolower($request["genre"]);
            $genre_arr = explode(',', $tmp);
            
            $genre_id = [];
            foreach ($genre_arr as $genre_name) {
                $genre = genres::firstOrCreate(['name' => $genre_name]);
                
                $genre_id = $genre->id;
            }
        }
        
        $title = strtolower($request["title"]);
        
        $books = DB::table('books')->insert(
            [
                'title' => $title,
                'author' => $request['author'],
                'publish' =>  $request['publish'],
            ]
        );


        return redirect('/admin/books');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // $book = Books::find($id);
        // $book->delete();

        $book = DB::table('books')->where('id',$id)->delete();
        return redirect()->back();
    }

    public function export() 
    {
        return Excel::download(new BooksExport, 'books.xlsx');
    }
}

resources/views/admin/layout/component/books/form.blade.php
@extends('admin.template.master')

@section('content')

<div class = "ml-4 mt-4 mr-4">
<div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Form Buku</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{ route('books.store') }}" method ="POST">
              @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" name="title" placeholder="Title">
                    @error('title')
                    <div class="alert alert-danger">
                    {{ $message }}
                    </div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="author">Author</label>
                    <input type="text" class="form-control" name="author" placeholder="Author">
                    @error('author')
                    <div class="alert alert-danger">
                    {{ $message }}
                    </div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="publish">Publish</label>
                    <input type="text" class="form-control" name="publish" placeholder="Publish">
                    @error('publish')
                    <div class="alert alert-danger">
                    {{ $message }}
                    </div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="genre">Genre</label>
                    <input type="text" class="form-control" name="genre" placeholder="romance, action, trhiller">
                    @error('genre')
                    <div class="alert alert-danger">
                    {{ $message }}
                    </div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Create</button>
                </div>
              </form>
            </div>
</div>

@endsection

resources/views/admin/layout/component/books/table.blade.php
@extends('admin.template.master')


@section('content')

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
<h1 class="h3 mb-2 text-gray-800">Selamat Datang</h1>
<a href="/excel-book" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
<i class="fas fa-download fa-sm text-white-50"></i> Download Excel</a>
</div>
<p class="mb-4">Welcome to TriBooks's Book List</p>
<p><a target="_blank" href="https://datatables.net">Learn More</a></p>
                    <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">TriBooks's Book List</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                        <a href="/admin/books/create" class="btn btn-info mb-2">Add Book</a>
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Title</th>
                                        <th>Author</th>
                                        <th>Publish</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($books as $b)
                                    <tr>
                                        <td>{{ $b->id}}</td>
                                        <td>{{ $b->title}}</td>
                                        <td>{{ $b->author}}</td>
                                        <td>{{ $b->publish}}</td>
                                        <td>
                                            <div class = "d-flex justify-content-around">
                                                <a href="/admin/books/{{ $b->id }}" class="btn btn-info">Show</a>
                                                <a href="/admin/books/{{ $b->id }}/edit" class="btn btn-primary">Edit</a>
                                                <form method="POST" action="/admin/books/{{ $b->id }}">
                                                    @csrf
                                                    @method('delete')
                                                    <input class="btn btn-danger" value="delete" type="submit">
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>


@endsection

@push('scripts')
<!--
<script>
    Swal.fire({
        title: "Data Berhasil Disimpan",
        text: "Terima Kasih Telah Mempercayai TriBooks",
        icon: "success",
        confirmButtonText: "Cilukba !!! linknya disini gan",
    });
    

    

    
</script>
-->
@endpush